# Run the linters with a baseline

name: FlakeHell

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install FlakeHell
        run: python -m install flakehell
      - name: Run FlakeHell
        run: poetry run flakehell lint
